'use client';
import { useEffect, useState } from 'react';

const nav = [{icon:'⌂',label:'Dashboard'},{icon:'▣',label:'Pembayaran SPP'},{icon:'▤',label:'Tabungan Siswa'},{icon:'♧',label:'Data Siswa'},{icon:'◫',label:'Laporan'}];
const activity = [
 {name:'Aisyah Putri', cls:'Kelas B · SPP Semester 1', amount:'Rp500.000', type:'SPP', time:'Hari ini, 09:42', color:'yellow'},
 {name:'Rafa Pratama', cls:'Kelas A · Setoran tabungan', amount:'Rp25.000', type:'TABUNGAN', time:'Hari ini, 09:15', color:'blue'},
 {name:'Naila Zahra', cls:'Kelas B · SPP Semester 1', amount:'Rp750.000', type:'SPP', time:'Kemarin, 14:20', color:'yellow'},
 {name:'Bima Arya', cls:'Kelas A · Penarikan tabungan', amount:'Rp100.000', type:'TABUNGAN', time:'Kemarin, 11:05', color:'red'}
];
export default function Home(){
 const [active,setActive]=useState('Dashboard');
 const [metrics,setMetrics]=useState({cashInThisMonth:0,totalArrears:0,activeStudents:0});
 useEffect(()=>{fetch('/api/dashboard/metrics').then(r=>r.ok?r.json():null).then(d=>d&&setMetrics(d)).catch(()=>{});},[]);
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><img src="/logo-paud.jpg"/><div><b>Cerdas Ceria</b><span>PAUD Finance</span></div></div><div className="school-pill"><span className="online-dot"/> SDM aktif <strong>24</strong></div><nav>{nav.map(n=><button key={n.label} className={active===n.label?'active':''} onClick={()=>{if(n.label==='Pembayaran SPP')window.location.href='/admin/spp';else if(n.label==='Data Siswa')window.location.href='/admin/master-data';else setActive(n.label)}}><i>{n.icon}</i>{n.label}</button>)}</nav><div className="sidebar-bottom"><button><i>⚙</i> Pengaturan</button><div className="profile"><div className="avatar">NA</div><div><b>Nur Aisyah</b><span>Bendahara</span></div><em>⋮</em></div></div></aside>
  <section className="content"><header><div className="breadcrumb">Beranda <span>/</span> {active}</div><div className="header-actions"><button className="icon-btn">⌕</button><button className="icon-btn notification">♢<span/></button><div className="date">◷ &nbsp; 20 September 2026</div></div></header>
   <div className="welcome"><div><p className="eyebrow">SABTU, 20 SEPTEMBER 2026</p><h1>Selamat pagi, Nur Aisyah <span>✦</span></h1><p className="muted">Kelola administrasi keuangan sekolah dengan mudah.</p></div><button className="primary">＋ Catat transaksi</button></div>
   <div className="stats"><Stat label="Kas masuk bulan ini" value={money(metrics.cashInThisMonth)} change="bulan ini" note="dari bulan lalu" icon="↗" tone="blue"/><Stat label="Saldo tabungan siswa" value="—" change="menunggu modul tabungan" note="dari bulan lalu" icon="▣" tone="yellow"/><Stat label="Total tunggakan SPP" value={money(metrics.totalArrears)} change="saldo berjalan" note="perlu ditindaklanjuti" icon="!" tone="red"/><Stat label="Siswa aktif" value={String(metrics.activeStudents)} change="siswa aktif" note="tahun ajaran 2026/27" icon="♧" tone="green"/></div>
   <div className="grid-main"><section className="panel chart-panel"><div className="panel-head"><div><h2>Arus kas masuk</h2><p>Ringkasan pemasukan 6 bulan terakhir</p></div><select><option>6 bulan terakhir</option></select></div><div className="chart"><div className="ylabels"><span>10 jt</span><span>7.5 jt</span><span>5 jt</span><span>2.5 jt</span><span>0</span></div><div className="chart-body"><div className="gridlines"><i/><i/><i/><i/><i/></div><svg viewBox="0 0 620 190" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#12a9e0" stopOpacity=".22"/><stop offset="1" stopColor="#12a9e0" stopOpacity="0"/></linearGradient></defs><path d="M0 147 C40 137, 55 123, 90 132 S140 113, 185 116 S225 93, 275 103 S320 72, 360 87 S410 52, 455 69 S500 34, 535 55 S580 25, 620 32 L620 190 L0 190Z" fill="url(#fill)"/><path d="M0 147 C40 137, 55 123, 90 132 S140 113, 185 116 S225 93, 275 103 S320 72, 360 87 S410 52, 455 69 S500 34, 535 55 S580 25, 620 32" fill="none" stroke="#079bd2" strokeWidth="3" strokeLinecap="round"/></svg><div className="months"><span>Apr</span><span>Mei</span><span>Jun</span><span>Jul</span><span>Agu</span><span>Sep</span></div></div></div></section>
   <section className="panel quick-panel"><div className="panel-head"><div><h2>Aksi cepat</h2><p>Jalankan tugas yang sering digunakan</p></div></div><div className="quick-list"><Quick icon="＋" title="Bayar SPP" desc="Catat pembayaran baru" tone="blue"/><Quick icon="↙" title="Setor tabungan" desc="Tambah saldo siswa" tone="yellow"/><Quick icon="↗" title="Tarik tabungan" desc="Catat penarikan" tone="pink"/><Quick icon="▤" title="Lihat laporan" desc="Rekap dan ekspor data" tone="green"/></div></section></div>
   <section className="panel activity"><div className="panel-head"><div><h2>Transaksi terbaru</h2><p>Aktivitas keuangan yang baru dicatat</p></div><button className="text-btn">Lihat semua →</button></div><div className="table"><div className="tr th"><span>SISWA</span><span>JENIS TRANSAKSI</span><span>NOMINAL</span><span>WAKTU</span><span>STATUS</span></div>{activity.map((a,i)=><div className="tr" key={i}><span className="student"><b className={'mini '+a.color}>{a.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</b><strong>{a.name}<small>{a.cls}</small></strong></span><span><label className={'tag '+a.color}>{a.type}</label></span><span className="amount">{a.amount}</span><span className="time">{a.time}</span><span><label className="status"><i/> Berhasil</label></span></div>)}</div></section>
   <footer><span>© 2026 Cerdas Ceria PAUD</span><span>Butuh bantuan? <b>Hubungi admin</b></span></footer>
  </section></main>
}
function money(n:number){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)}
function Stat({label,value,change,note,icon,tone}:{label:string,value:string,change:string,note:string,icon:string,tone:string}){return <div className="stat"><div className={'stat-icon '+tone}>{icon}</div><p>{label}</p><h3>{value}</h3><div className="stat-note"><b className={tone==='red'?'bad':''}>{change}</b> {note}</div></div>}
function Quick({icon,title,desc,tone}:{icon:string,title:string,desc:string,tone:string}){return <button className="quick"><span className={'quick-icon '+tone}>{icon}</span><span><b>{title}</b><small>{desc}</small></span><em>›</em></button>}
