'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Banknote, BookOpen, Check, Home, LoaderCircle, LogOut, ReceiptText, UserRound, UsersRound, X } from 'lucide-react';

type Child={id:string;name:string;className:string};

export default function ParentShell({children}:{children:React.ReactNode}){
  const pathname=usePathname(),router=useRouter();
  const[parent,setParent]=useState<any>(null),[school,setSchool]=useState('Sekolah'),[students,setStudents]=useState<Child[]>([]),[selected,setSelected]=useState(''),[pickerOpen,setPickerOpen]=useState(false),[loggingOut,setLoggingOut]=useState(false);
  useEffect(()=>{fetch('/api/wali/me').then(async r=>{if(r.status===401){router.replace('/wali/login');return null}if(!r.ok)throw Error();return r.json()}).then(d=>{if(!d)return;setParent(d.parent);setSchool(d.school?.name||'Sekolah');setStudents(d.students);const saved=sessionStorage.getItem('wali-student-id');setSelected(d.students.some((x:Child)=>x.id===saved)?saved:d.students[0]?.id||'')}).catch(()=>router.replace('/wali/login'))},[router]);
  useEffect(()=>{document.body.style.overflow=pickerOpen?'hidden':'';return()=>{document.body.style.overflow=''}},[pickerOpen]);
  useEffect(()=>{if(!selected)return;sessionStorage.setItem('wali-student-id',selected);window.dispatchEvent(new CustomEvent('wali-student-change',{detail:selected}));const query=`?studentId=${encodeURIComponent(selected)}`;if(pathname==='/wali'||pathname.startsWith('/wali/spp')||pathname.startsWith('/wali/tabungan')||pathname.startsWith('/wali/akun'))router.replace(`${pathname}${query}`)},[selected,pathname,router]);
  async function logout(){if(loggingOut)return;setLoggingOut(true);try{const r=await fetch('/api/auth/parent-logout',{method:'POST'});if(!r.ok)throw Error();router.replace('/wali/login')}catch{setLoggingOut(false)}}
  if(!parent)return <div className="parent-loading"><LoaderCircle className="loading-spinner" size={24}/> Memuat buku digital...</div>;
  const hasChildren=students.length>0,active=students.find(x=>x.id===selected);
  return <div className="parent-portal"><header className="parent-header"><div><b>{school}</b><span>Halo, {parent.name}</span></div>{students.length>1&&<button className="parent-switcher-trigger" onClick={()=>setPickerOpen(true)}><UsersRound size={16}/><span>Ganti Anak</span></button>}</header><main className="parent-content">{hasChildren?children:<section className="parent-no-child"><BookOpen size={34}/><h1>Belum ada data anak</h1><p>Belum ada data anak yang terhubung ke akun ini.</p><small>Silakan hubungi pihak sekolah untuk memperbarui data.</small></section>}</main><nav className="parent-bottom-nav" aria-label="Navigasi buku digital"><Link className={pathname==='/wali'?'active':''} href={hasChildren?`/wali?studentId=${selected}`:'/wali'}><Home size={20}/><span>Beranda</span></Link><Link className={pathname.startsWith('/wali/spp')?'active':''} href={hasChildren?`/wali/spp?studentId=${selected}`:'/wali/spp'}><ReceiptText size={20}/><span>SPP</span></Link><Link className={pathname.startsWith('/wali/tabungan')?'active':''} href={hasChildren?`/wali/tabungan?studentId=${selected}`:'/wali/tabungan'}><Banknote size={20}/><span>Tabungan</span></Link><Link className={pathname.startsWith('/wali/akun')?'active':''} href={`/wali/akun?studentId=${selected}`}><UserRound size={20}/><span>Akun</span></Link></nav>{pickerOpen&&<div className="parent-sheet-backdrop"><section className="parent-child-sheet" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label="Pilih anak"><div className="parent-sheet-handle"/><div className="parent-sheet-head"><h2>Pilih Anak</h2><button onClick={()=>setPickerOpen(false)} aria-label="Tutup"><X size={18}/></button></div>{students.map(child=><button className={`parent-child-option ${child.id===selected?'selected':''}`} key={child.id} onClick={()=>{setSelected(child.id);setPickerOpen(false)}}><span><b>{child.name}</b><small>{child.className}</small></span>{child.id===selected&&<Check className="parent-child-check" size={18} aria-label="Anak aktif"/>}</button>)}</section></div>}</div>;
}
