'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Banknote, Home, LoaderCircle, LogOut, ReceiptText } from 'lucide-react';

type Child = { id: string; name: string; className: string };
export default function ParentShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const [parent, setParent] = useState<any>(null); const [students, setStudents] = useState<Child[]>([]); const [selected, setSelected] = useState(''); const [loggingOut, setLoggingOut] = useState(false);
  useEffect(() => { fetch('/api/wali/me').then(async (r) => { if (r.status === 401) { router.replace('/wali/login'); return null; } if (!r.ok) throw Error(); return r.json(); }).then((d) => { if (!d) return; setParent(d.parent); setStudents(d.students); const saved = window.sessionStorage.getItem('wali-student-id'); setSelected(d.students.some((x: Child) => x.id === saved) ? saved : d.students[0]?.id ?? ''); }).catch(() => router.replace('/wali/login')); }, [router]);
  useEffect(() => { if (selected) { window.sessionStorage.setItem('wali-student-id', selected); window.dispatchEvent(new CustomEvent('wali-student-change', { detail: selected })); if (pathname.startsWith('/wali/spp')) router.replace(`/wali/spp?studentId=${selected}`); if (pathname.startsWith('/wali/tabungan')) router.replace(`/wali/tabungan?studentId=${selected}`); } }, [selected, pathname, router]);
  async function logout() { if (loggingOut) return; setLoggingOut(true); try { const r = await fetch('/api/auth/parent-logout', { method: 'POST' }); if (!r.ok) throw Error(); router.replace('/wali/login'); } catch { setLoggingOut(false); } }
  if (!parent || !selected) return <div className="parent-loading"><LoaderCircle className="loading-spinner" size={24}/> Memuat buku digital...</div>;
  return <div className="parent-portal"><header className="parent-header"><div><b>PAUD Cerdas Ceria</b><span>Halo, {parent.name}</span></div><button className="parent-logout" onClick={logout} disabled={loggingOut}>{loggingOut ? <LoaderCircle className="loading-spinner" size={17}/> : <LogOut size={17}/>}<span>{loggingOut ? 'Keluar...' : 'Keluar'}</span></button></header>{students.length > 1 && <label className="child-picker"><span>Anak aktif</span><select value={selected} onChange={(e) => setSelected(e.target.value)}>{students.map((child) => <option key={child.id} value={child.id}>{child.name} · {child.className}</option>)}</select></label>}<main className="parent-content">{children}</main><nav className="parent-bottom-nav" aria-label="Navigasi buku digital"><Link className={pathname === '/wali' ? 'active' : ''} href="/wali"><Home size={20}/><span>Beranda</span></Link><Link className={pathname.startsWith('/wali/spp') ? 'active' : ''} href={`/wali/spp?studentId=${selected}`}><ReceiptText size={20}/><span>SPP</span></Link><Link className={pathname.startsWith('/wali/tabungan') ? 'active' : ''} href={`/wali/tabungan?studentId=${selected}`}><Banknote size={20}/><span>Tabungan</span></Link></nav></div>;
}
