import crypto from'node:crypto';import{cookies}from'next/headers';import{prisma}from'./prisma';import{ALL_PERMISSION_KEYS}from'./permissions';
export const ADMIN_SESSION_COOKIE='paud_session';export const PARENT_SESSION_COOKIE='paud_parent_session';const SESSION_DAYS=30;
export function createToken(){return crypto.randomBytes(32).toString('hex')}export function hashToken(token:string){return crypto.createHash('sha256').update(token).digest('hex')}function expiry(){const d=new Date();d.setDate(d.getDate()+SESSION_DAYS);return d}
export async function createAdminSession(userId:string){const token=createToken();await prisma.authSession.create({data:{userId,tokenHash:hashToken(token),expiresAt:expiry()}});return token}
export async function createParentSession(parentId:string){const token=createToken();await prisma.parentSession.create({data:{parentId,tokenHash:hashToken(token),expiresAt:expiry()}});return token}
export async function getCurrentUser(){const token=cookies().get(ADMIN_SESSION_COOKIE)?.value;if(!token)return null;const session=await prisma.authSession.findUnique({where:{tokenHash:hashToken(token)},include:{user:{include:{roles:{include:{role:{include:{permissions:{include:{permission:true}}}}}}}}}});if(!session||session.expiresAt<new Date()||session.user.status!=='ACTIVE')return null;return session.user}
export async function getCurrentParent(){const token=cookies().get(PARENT_SESSION_COOKIE)?.value;if(!token)return null;const session=await prisma.parentSession.findUnique({where:{tokenHash:hashToken(token)},include:{parent:true}});if(!session||session.expiresAt<new Date())return null;return session.parent}
export const sessionCookie=(name:string,token:string)=>({name,value:token,httpOnly:true,sameSite:'lax'as const,secure:process.env.NODE_ENV==='production',path:'/',maxAge:SESSION_DAYS*24*60*60});
export function getEffectivePermissionKeys(user:NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>){if(user.roles.some(x=>x.role.name==='SUPER_ADMIN'))return[...ALL_PERMISSION_KEYS];return Array.from(new Set(user.roles.flatMap(x=>x.role.permissions.map(p=>p.permission.key))))}
export async function hasPermission(key:string){const user=await getCurrentUser();if(!user)return false;if(user.roles.some(x=>x.role.name==='SUPER_ADMIN'))return true;return getEffectivePermissionKeys(user).includes(key)}
export async function hasAllPermissions(keys:string[]){const user=await getCurrentUser();if(!user)return false;if(user.roles.some(x=>x.role.name==='SUPER_ADMIN'))return true;const set=new Set(getEffectivePermissionKeys(user));return keys.every(k=>set.has(k))}
export async function hasAnyPermission(keys:string[]){const user=await getCurrentUser();if(!user)return false;if(user.roles.some(x=>x.role.name==='SUPER_ADMIN'))return true;const set=new Set(getEffectivePermissionKeys(user));return keys.some(k=>set.has(k))}
